global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'greenlight-train'
    static_configs:
      - targets: ['host.docker.internal:8001']
        labels:
          stage: 'train'
          project: 'mlops-greenlight'

